# Generated by Django 5.0.4 on 2024-09-24 01:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        ('users', '0002_user_comment_polarity_user_post_polarity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='post_likes',
            field=models.ManyToManyField(related_name='liked_by', to='post.post'),
        ),
        migrations.AddField(
            model_name='user',
            name='post_love',
            field=models.ManyToManyField(related_name='loved_by', to='post.post'),
        ),
    ]
